setInterval(function change() {
    var img = document.getElementById("imgs"),
        imgr = document.getElementById("imgr"),
        imgs = [
            "./imgs/1.jpg",
            "./imgs/2.jpg",
            "./imgs/3.jpg",
            "./imgs/4.jpg",
            "./imgs/5.jpg",
            "./imgs/6.jpg",
            "./imgs/7.jpg",
			"./imgs/8.jpg",
            "./imgs/9.jpg",
            "./imgs/10.jpg",
			"./imgs/11.jpg",
			"./imgs/12.jpg",
			"./imgs/13.jpg",
			"./imgs/14.jpg",
			"./imgs/15.jpg",
			"./imgs/16.jpg",
			"./imgs/17.jpg",
			"./imgs/18.jpg",
			"./imgs/19.jpg",
			"./imgs/20.jpg",
			"./imgs/21.jpg",
			"./imgs/22.jpg",
			"./imgs/23.jpg",
			"./imgs/24.jpg",
			"./imgs/25.jpg",
			"./imgs/26.jpg",
			"./imgs/27.jpg",
			"./imgs/28.jpg",
			"./imgs/29.jpg",
			"./imgs/30.jpg",
			"./imgs/31.jpg",
			"./imgs/32.jpg",
			"./imgs/33.jpg",
			"./imgs/34.jpg",
			"./imgs/35.jpg",
			"./imgs/36.jpg",
			"./imgs/37.jpg",
			"./imgs/38.jpg",
			"./imgs/39.jpg",
			"./imgs/40.jpg",
        ],
        link = [

            "https://buzzmavo.com/",
            "https://buzzmavo.com/2021/09/11/subway-surfers/",
            "https://buzzmavo.com/",
            "https://buzzmavo.com/",
            "https://buzzmavo.com/2021/09/26/go-up-dash-geometry-dash-meltdown/",
            "https://buzzmavo.com/",
            "https://buzzmavo.com/",
			"https://buzzmavo.com/",
            "https://buzzmavo.com/2021/08/20/moto-maniac-3/",
            "https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/category/girls/",
			"https://buzzmavo.com/",
			"https://buzzmavo.com/",
        ]
    limgs = imgs.length,
        ran = Math.floor(Math.random() * limgs),
        randsrc = imgr.setAttribute("src", imgs[ran]); // or imgr.src = 
    randlink = links.setAttribute("href", link[ran]);
}, 2000);