const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Button,
		C3.Plugins.Share,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Behaviors.Orbit,
		C3.Plugins.GM_SDK,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Share.Cnds.IsSharingFilesSupported,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Share.Acts.AddFile,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.Sprite.Acts.SetMeshSize,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.MeshColumns,
		C3.Plugins.Sprite.Exps.MeshRows,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Piggy: 0},
	{MeshColumn: 0},
	{MeshRow: 0},
	{DragDrop: 0},
	{MeshPoint: 0},
	{Text: 0},
	{Sprite: 0},
	{Touch: 0},
	{ScreenshotSprite: 0},
	{TakeScreenshotButton: 0},
	{DownloadButton: 0},
	{ShareButton: 0},
	{Share: 0},
	{ShareStatus: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{Browser: 0},
	{downloadbtn: 0},
	{takeshot: 0},
	{sharebtn: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{sharebtn2: 0},
	{hidedots: 0},
	{hidedots2: 0},
	{SpriteFont: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sine: 0},
	{PLAY: 0},
	{Sprite7: 0},
	{reset: 0},
	{Sprite8: 0},
	{trump: 0},
	{Sprite9: 0},
	{biden: 0},
	{Sprite10: 0},
	{HOME: 0},
	{putin: 0},
	{djokovic: 0},
	{lopez: 0},
	{ronaldo: 0},
	{more: 0},
	{Mouse: 0},
	{Sprite12: 0},
	{HOME2: 0},
	{BSound: 0},
	{Audio: 0},
	{y8: 0},
	{Loginy8: 0},
	{listAchievements: 0},
	{unlockAchievement: 0},
	{listScores: 0},
	{saveScore: 0},
	{saveData: 0},
	{getData: 0},
	{openProfile: 0},
	{gameBreak: 0},
	{screenshot: 0},
	{playerName: 0},
	{scoreTxt: 0},
	{addScore: 0},
	{SALJI: 0},
	{Loginy8moja: 0},
	{y8profile: 0},
	{Sprite11: 0},
	{trumpnevidljividugme: 0},
	{putinnevidljividugme2: 0},
	{HOME3: 0},
	{Sprite13: 0},
	{kolindanevidljividugme3: 0},
	{bushnevidljividugme4: 0},
	{beannevidljividugme5: 0},
	{leonardonevidljividugme6: 0},
	{rocknevidljividugme7: 0},
	{visetacaka: 0},
	{moregames: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{igraj: 0},
	{vatromet: 0},
	{Sprite19: 0},
	{Fireflies: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Orbit: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{lagged: 0},
	{btn_camera: 0},
	{GameMonetizeSDK: 0},
	{buttons: 0},
	{PiggyLeft: 0},
	{PiggyTop: 0},
	{PiggyRight: 0},
	{PiggyBottom: 0},
	{sound: 0},
	{SoundEf: 0},
	{score: 0}
];

self.InstanceType = {
	Piggy: class extends self.ISpriteInstance {},
	MeshPoint: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ScreenshotSprite: class extends self.ISpriteInstance {},
	TakeScreenshotButton: class extends self.IButtonInstance {},
	DownloadButton: class extends self.IButtonInstance {},
	ShareButton: class extends self.IButtonInstance {},
	Share: class extends self.IInstance {},
	ShareStatus: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Browser: class extends self.IInstance {},
	downloadbtn: class extends self.ISpriteInstance {},
	takeshot: class extends self.ISpriteInstance {},
	sharebtn: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	sharebtn2: class extends self.ISpriteInstance {},
	hidedots: class extends self.ISpriteInstance {},
	hidedots2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	reset: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	trump: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	biden: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	HOME: class extends self.ISpriteInstance {},
	putin: class extends self.ISpriteInstance {},
	djokovic: class extends self.ISpriteInstance {},
	lopez: class extends self.ISpriteInstance {},
	ronaldo: class extends self.ISpriteInstance {},
	more: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	HOME2: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	y8: class extends self.ISpriteInstance {},
	Loginy8: class extends self.IButtonInstance {},
	listAchievements: class extends self.IButtonInstance {},
	unlockAchievement: class extends self.IButtonInstance {},
	listScores: class extends self.IButtonInstance {},
	saveScore: class extends self.IButtonInstance {},
	saveData: class extends self.IButtonInstance {},
	getData: class extends self.IButtonInstance {},
	openProfile: class extends self.IButtonInstance {},
	gameBreak: class extends self.IButtonInstance {},
	screenshot: class extends self.IButtonInstance {},
	playerName: class extends self.ITextInstance {},
	scoreTxt: class extends self.ITextInstance {},
	addScore: class extends self.IButtonInstance {},
	SALJI: class extends self.IButtonInstance {},
	Loginy8moja: class extends self.ISpriteInstance {},
	y8profile: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	trumpnevidljividugme: class extends self.ISpriteInstance {},
	putinnevidljividugme2: class extends self.ISpriteInstance {},
	HOME3: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	kolindanevidljividugme3: class extends self.ISpriteInstance {},
	bushnevidljividugme4: class extends self.ISpriteInstance {},
	beannevidljividugme5: class extends self.ISpriteInstance {},
	leonardonevidljividugme6: class extends self.ISpriteInstance {},
	rocknevidljividugme7: class extends self.ISpriteInstance {},
	visetacaka: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	igraj: class extends self.ISpriteInstance {},
	vatromet: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	lagged: class extends self.ISpriteInstance {},
	btn_camera: class extends self.ISpriteInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	buttons: class extends self.ISpriteInstance {}
}