const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.filechooser,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Share,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Plugins.FileSystem,
		C3.Plugins.GM_SDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Audio.Acts.SetLooping,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.BBoxLeft,
		C3.Plugins.DrawingCanvas.Exps.PixelScale,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.DrawingCanvas.Exps.BBoxTop,
		C3.JavaScriptInEvents["Bucket-Paint_Event12_Act5"],
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.JavaScriptInEvents["Bucket-Paint_Event13_Act5"],
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.JavaScriptInEvents["Bucket-Paint_Event17_Act1"],
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.filechooser.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnURLLoaded,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Share.Cnds.IsSharingFilesSupported,
		C3.Plugins.Share.Acts.AddFile,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.JavaScriptInEvents["Brush-Paint_Event23_Act1"],
		C3.Plugins.DrawingCanvas.Acts.SetPosToObject,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Button.Acts.SetBlur,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Exps.IID,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.DrawingCanvas.Acts.MoveToLayer,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.FileSystem.Cnds.OnPickerComplete,
		C3.Plugins.FileSystem.Acts.WriteBinaryFile,
		C3.Plugins.GM_SDK.Acts.ShowAd,
		C3.Plugins.GM_SDK.Cnds.PauseGame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{DrawingCanvas: 0},
	{Mouse: 0},
	{Browser: 0},
	{Image: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{ColorSprite: 0},
	{Frame: 0},
	{FileChooser: 0},
	{type: 0},
	{LoadButton: 0},
	{BrushSelector: 0},
	{ButtonRestart: 0},
	{BrushSelect: 0},
	{ColorSelect: 0},
	{CanvasTemp: 0},
	{Stencil: 0},
	{Canvas: 0},
	{Button: 0},
	{BG: 0},
	{Touch: 0},
	{Paint: 0},
	{ColorSelector: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Image2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Background: 0},
	{homebtn: 0},
	{pozadinazvuk: 0},
	{BSound: 0},
	{Sprite6: 0},
	{ponovo1: 0},
	{Sine: 0},
	{ponovo: 0},
	{pozadinabijela: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{SpriteFont: 0},
	{takeshot: 0},
	{ScreenshotSprite: 0},
	{sharebtn: 0},
	{downloadbtn: 0},
	{sharebtn2: 0},
	{AJAX: 0},
	{ShareButton: 0},
	{DownloadButton: 0},
	{TakeScreenshotButton: 0},
	{BinaryData: 0},
	{Share: 0},
	{pozadinazvuk2: 0},
	{pozadinazvuk3: 0},
	{DragDrop: 0},
	{stamp: 0},
	{Sprite7: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{PRVABUCKET: 0},
	{PRVABRUSH: 0},
	{DRUGABUCKET: 0},
	{DRUGABRUSH: 0},
	{TRECABRUSH: 0},
	{TRECABUCKET: 0},
	{Sprite17: 0},
	{CETVRTABUCKET: 0},
	{CETVRTABRUSH: 0},
	{Sprite18: 0},
	{PETABRUSH: 0},
	{PETABUCKET: 0},
	{Sprite19: 0},
	{SESTABUCKET: 0},
	{SESTABRUSH: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Audio: 0},
	{REWARDMEDO: 0},
	{REWARDDJECAK: 0},
	{okidac: 0},
	{moregames: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{snjesko: 0},
	{snijeg: 0},
	{igrajdugme: 0},
	{pozadina123: 0},
	{logo123: 0},
	{paleta: 0},
	{olovke: 0},
	{olovka: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{addtimereklama: 0},
	{pozadinazarewardedads: 0},
	{pozadinazarewardedads2: 0},
	{LanguageData: 0},
	{TextIndex: 0},
	{Pin: 0},
	{TextFont: 0},
	{zid: 0},
	{LanguageIndex: 0},
	{Tween: 0},
	{Flag: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{okvir: 0},
	{okvir2: 0},
	{Santa: 0},
	{signplakat: 0},
	{TextFont2: 0},
	{zarewardedtrigger: 0},
	{FileSystem: 0},
	{GameMonetizeSDK: 0},
	{buttons: 0},
	{x: 0},
	{y: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{tolerance: 0},
	{OffsetSpeed: 0},
	{MAX_IMAGE_SIZE: 0},
	{s: 0},
	{CurrentBrush: 0},
	{CurrentColor: 0},
	{sound: 0},
	{SoundEf: 0}
];

self.InstanceType = {
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Image: class extends self.ISpriteInstance {},
	ColorSprite: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	FileChooser: class extends self.IFileChooserInstance {},
	LoadButton: class extends self.IButtonInstance {},
	BrushSelector: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.IButtonInstance {},
	BrushSelect: class extends self.ISpriteInstance {},
	ColorSelect: class extends self.ISpriteInstance {},
	CanvasTemp: class extends self.IDrawingCanvasInstance {},
	Stencil: class extends self.ISpriteInstance {},
	Canvas: class extends self.IDrawingCanvasInstance {},
	Button: class extends self.IButtonInstance {},
	BG: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Paint: class extends self.ISpriteInstance {},
	ColorSelector: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Image2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	homebtn: class extends self.ISpriteInstance {},
	pozadinazvuk: class extends self.ISpriteInstance {},
	BSound: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ponovo1: class extends self.ISpriteInstance {},
	ponovo: class extends self.ISpriteInstance {},
	pozadinabijela: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	takeshot: class extends self.ISpriteInstance {},
	ScreenshotSprite: class extends self.ISpriteInstance {},
	sharebtn: class extends self.ISpriteInstance {},
	downloadbtn: class extends self.ISpriteInstance {},
	sharebtn2: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	ShareButton: class extends self.IButtonInstance {},
	DownloadButton: class extends self.IButtonInstance {},
	TakeScreenshotButton: class extends self.IButtonInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Share: class extends self.IInstance {},
	pozadinazvuk2: class extends self.ISpriteInstance {},
	pozadinazvuk3: class extends self.ISpriteInstance {},
	stamp: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	PRVABUCKET: class extends self.ISpriteInstance {},
	PRVABRUSH: class extends self.ISpriteInstance {},
	DRUGABUCKET: class extends self.ISpriteInstance {},
	DRUGABRUSH: class extends self.ISpriteInstance {},
	TRECABRUSH: class extends self.ISpriteInstance {},
	TRECABUCKET: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	CETVRTABUCKET: class extends self.ISpriteInstance {},
	CETVRTABRUSH: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	PETABRUSH: class extends self.ISpriteInstance {},
	PETABUCKET: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	SESTABUCKET: class extends self.ISpriteInstance {},
	SESTABRUSH: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	REWARDMEDO: class extends self.ISpriteInstance {},
	REWARDDJECAK: class extends self.ISpriteInstance {},
	okidac: class extends self.ISpriteInstance {},
	moregames: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	snjesko: class extends self.ISpriteInstance {},
	snijeg: class extends self.ISpriteInstance {},
	igrajdugme: class extends self.ISpriteInstance {},
	pozadina123: class extends self.ISpriteInstance {},
	logo123: class extends self.ISpriteInstance {},
	paleta: class extends self.ISpriteInstance {},
	olovke: class extends self.ISpriteInstance {},
	olovka: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	addtimereklama: class extends self.ISpriteInstance {},
	pozadinazarewardedads: class extends self.ISpriteInstance {},
	pozadinazarewardedads2: class extends self.ISpriteInstance {},
	LanguageData: class extends self.IArrayInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	zid: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	okvir: class extends self.ISpriteInstance {},
	okvir2: class extends self.ISpriteInstance {},
	Santa: class extends self.ISpriteInstance {},
	signplakat: class extends self.ISpriteInstance {},
	TextFont2: class extends self.ISpriteFontInstance {},
	zarewardedtrigger: class extends self.ISpriteInstance {},
	FileSystem: class extends self.IInstance {},
	GameMonetizeSDK: class extends C3.Plugins.GM_SDK.Instance {},
	buttons: class extends self.ISpriteInstance {}
}