var GAME_NAME = "kittygram";

var CANVAS_WIDTH = 1920;
var CANVAS_HEIGHT = 1920;

var EDGEBOARD_X = 0;
var EDGEBOARD_Y = 0;

var FONT = "Dosis";

var ENABLE_FULLSCREEN;

var FPS      = 60;
var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_CHOOSE_LEVEL    = 2;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_BUT_YES_DOWN  = 4;
var ON_BUT_NO_DOWN  = 5;
var ON_SELECT_PIECE = 6;
var ON_CELL_PRESS = 7;
var ON_LEVEL_WIN = 8;
var ON_HINT = 9;
var ON_HELP = 10;

var DIR_LEFT = 0;
var DIR_TOP = 1;
var DIR_RIGHT = 2;
var DIR_BOTTOM = 3;

var LABEL_UNAVAILABLE = -1;
var LABEL_EMPTY = 0;
var LABEL_FILL = 1;

var CUR_GRID_SCALE = 1;
var MAX_TABLE_HEIGHT_LANDSCAPE = 1640;
var MAX_TABLE_WIDTH_PORTRAIT = 1140;
var MAX_TABLE_HEIGHT = 1802;
var NUM_ROWS = 10;
var NUM_COLS = 10;
var CELL_WIDTH = 108;
var CELL_HEIGHT = 108;
var CELL_HEIGHT_FAKE = 93;
var CELL_X = 70;
var CELL_Y = 98;
var NUM_PIECES;
var PIECE_TO_PLACE;
var NUM_TYPES = 10;
var X_PIECE_ATTACH = 555;
var Y_PIECE_ATTACH = CANVAS_HEIGHT/2+180;
var SCALE_STARTING_PIECE = 0.6;
var OFFSET_PIECE_Y = 250;
var SOUNDTRACK_VOLUME_IN_GAME = 0.2;
var MIN_TIME_IDLE = 5000;
var MAX_TIME_IDLE = 30000;
var NUM_ROWS_PER_PAGE = 3;
var NUM_COLS_PER_PAGE = 4;
var MALUS_HINT;
var MAX_FREE_HINTS = 1;